// Importa un archivo de estilos globales y tipos de datos desde las bibliotecas de Next.js.
import "./globals.css";
import type { Metadata } from "next";
// Importa la fuente Inter desde la biblioteca next/font/google.
import { Inter } from "next/font/google";
// Importa el componente Navbar desde la ruta relativa "@/components/Navbar".
import Navbar from "@/components/Navbar";
// Importa el componente Providers desde el archivo './Providers'.
import {Providers} from './Providers'

// Crea una instancia de la fuente Inter con el subconjunto "latin".
const inter = Inter({ subsets: ["latin"] });

// Define metadatos para la página.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define un componente de función RootLayout que recibe un objeto con una propiedad children y retorna JSX.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
